<?php
$query_pedidos_status = $conn->prepare("SELECT * FROM(
										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 1
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 2
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 3
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 4
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 7
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 8
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 9
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 10
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 11
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 12
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 13
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 14
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 15
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 16
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 17
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 18
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 19
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 20
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 21
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 22
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 23
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 24
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 25
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 26
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 27
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 28
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 29
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 30
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 31
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 32
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A
										INNER JOIN AM_STATUSORDEM B ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 33
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 34
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 

										UNION

										SELECT B.NOME STATUS, COUNT(A.HANDLE) QUANTIDADE
										FROM AM_ORDEM A (NOLOCK)
										INNER JOIN AM_STATUSORDEM B (NOLOCK) ON B.HANDLE = A.STATUS
										WHERE A.STATUS = 35
										AND NATUREZAOPERACAO IN (4,5)
										GROUP BY B.NOME 
										) AS STATUSTAB
										ORDER BY 1 ASC
										") or die('Não foi possível executar o Select');
				$query_pedidos_status->execute();


				while ($row_pedidos_status = $query_pedidos_status->fetch(PDO::FETCH_ASSOC)) {
					$status_pedidos_status = $row_pedidos_status['STATUS'];
					$quantidade_pedidos_status = $row_pedidos_status['QUANTIDADE'];
			?>
				<tr>
					<td><?php echo $status_pedidos_status; ?></td>
					<td style="color: red;"><?php echo $quantidade_pedidos_status; ?></td>
				</tr>
			<?php
				}
			?>